# Syft SBOM Configuration
# Generate SBOM with: syft . -o spdx-json=sbom.spdx.json
# https://github.com/anchore/syft

# Output format options: spdx-json, cyclonedx-json, syft-json
output:
  - "spdx-json=sbom.spdx.json"
  - "cyclonedx-json=sbom.cyclonedx.json"

# Cataloger scope - scan all layers for complete SBOM
scope: "all-layers"

# File selection
file:
  selection: "owned-by-package"
  metadata:
    selection: "all"
    digests:
      - "sha256"

# Package configuration
package:
  search-indexed-archives: true
  search-unindexed-archives: false

# Source configuration
source:
  # Metadata to include about the scanned source
  name: "home-registry"
  version: "0.1.0-beta.2"
  
# Exclude paths from scanning
exclude:
  - "**/node_modules/**"
  - "**/target/**"
  - "**/.git/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/.cache/**"
  - "**/tmp/**"
  - "**/temp/**"
  - "**/*.log"
  - "./analysis/**"

# Parallelism for scanning
parallelism: 4

# Log level
log:
  verbosity: 0
  level: "warn"
